# Site settings
title: TerminalStar
email: katherine.smith1234@googlemail.com
description: > # this means to ignore newlines until "baseurl:"
    Look at this fun stuff I have done!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: TerminalStar
github_username:  TerminalStar

# Build settings
markdown: kramdown
